server:
  port: 10013
spring:
  application:
    name: consul-client
  cloud:
    consul:
      #consul server端的地址和端口号
      host: localhost
      port: 8500
      #本服务的心跳地址以及注册到consul上的服务名称
      discovery:
        health-check-url: http://localhost:10013/actuator/health
        service-name: consul-client
    discovery:
      client:
        health-indicator:
          enabled: true
