server:
  port: 10020
spring:
  application:
    name: consul-feign
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-url: http://localhost:10020/actuator/health
        service-name: consul-feign
    discovery:
      client:
        health-indicator:
          enabled: true
