server:
  port: 10015
spring:
  application:
    name: consul-consumer
  cloud:
    consul:
      host: 192.168.1.4
      port: 8500
      discovery:
        health-check-url: http://192.168.1.4:10015/actuator/health
        service-name: consul-consumer
    discovery:
      client:
        health-indicator:
          enabled: true
