server:
  port: 10014
spring:
  application:
    name: consul-client10013
  cloud:
    consul:
      host: 192.168.1.4
      port: 8500
      discovery:
        health-check-url: http://192.168.1.4:10014/actuator/health
        service-name: consul-client10013
    discovery:
      client:
        health-indicator:
          enabled: true
