server:
  port: 10030
spring:
  application:
    name: consul-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JerryDtj/springcloudgreenwich.git
          search-paths: config-repo
