server:
  port: 10015
spring:
  application:
    name: consul-client-jerry
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-url: http://localhost:10015/actuator/health
        service-name: consul-client-jerry
    discovery:
      client:
        health-indicator:
          enabled: true
